name: CI Test Suite

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --filter "Category!=Integration&Category!=EndToEnd" --logger "trx;LogFileName=unit-test-results.trx" --verbosity normal

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: '**/unit-test-results.trx'

  build-validation:
    name: Build Validation
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build in Release mode
        run: dotnet build --no-restore --configuration Release

      - name: Verify build succeeded
        run: |
          echo "Build completed successfully in Release mode"
